<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <PackageId>OpsDash.Core.WebApi</PackageId>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OpsDash.Core.Auth\OpsDash.Core.Auth.csproj" />
      <ProjectReference Include="..\OpsDash.Core.OpenApi\OpsDash.Core.OpenApi.csproj" />
    </ItemGroup>

</Project>