name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  pipeline:
    uses: opsdash/pipelines/.github/workflows/dotnet-orchestrate.yaml
